### ISSUE TITLE
Radius of first Fresnel ellipsoid

### ISSUE THREAD

**Issue by mplussier** [eeveetza/p530#1]
Hi Dr. Stevanovic,
it seems that some parentheses are missing at line 234 of P530.m, which affects the results.
I think it should be
F1 = 17.3 * sqrt(d1*d2/(f*(d1 + d2)));
instead of
F1 = 17.3 * sqrt(d1*d2/f*(d1 + d2));

Best regards

**Comment by eeveetza** [comment]
You are right. The above [patch](https://github.com/eeveetza/p530/commit/437262977b176fd80bfeeadf352261bb032b9775) resolves the issue, which can be closed now. Many thanks.
